### ISSUE TITLE
Add capability to verify the content from PDF file

### ISSUE THREAD

**Issue by Ngaur** [Creative-Lab/AutoTestPlatform#13]
**Description :**
- User must be able to write step to verify text in PDF file.
- User can apply test step strategy as well.
- File would be automatically picked from "external files" relative location.
- typical inputs would be 1. File name 2. text to verify 3. page number to verify text (OPTIONAL).
- If page number is not given then whole file would be scanned.

**Comment by RahulKumarDantalwal** [comment]
Issue implemented with these functionality:-
     \* verify text from whole file:- @A verifyPdfText; @D filename#texttoverify;
     \* verify text from page number file:- @A verifyPdfText; @D filename#texttoverify#pagenumber;
     \* verify text from range of page:- @A verifyPdfText; @D filename#texttoverify#startpagenumber to endpagenumber;

pull request is #12
